const bemidbarChapters = [
  {
    key: 1,
    chapterName: "БЕМИДБАР (В пустыни)",
    start: 0,
    end: 53,
    verses: 54,
  },
  {
    key: 2,
    chapterName: "БЕМИДБАР (В пустыни)",
    start: 54,
    end: 87,
    verses: 34,
  },
  {
    key: 3,
    chapterName: "БЕМИДБАР (В пустыни)",
    start: 88,
    end: 138,
    verses: 51,
  },
  {
    key: 4,
    chapterName: "БЕМИДБАР (В пустыни)",
    start: 139,
    end: 187,
    verses: 49,
  },
  {
    key: 5,
    chapterName: "НАСО (Вознеси)",
    start: 188,
    end: 218,
    verses: 31,
  },
  {
    key: 6,
    chapterName: "НАСО (Вознеси)",
    start: 219,
    end: 245,
    verses: 27,
  },
  {
    key: 7,
    chapterName: "НАСО (Вознеси)",
    start: 246,
    end: 334,
    verses: 89,
  },
  {
    key: 8,
    chapterName: "БЕААЛОТХА (Когда будешь возжигать)",
    start: 335,
    end: 360,
    verses: 26,
  },
  {
    key: 9,
    chapterName: "БЕААЛОТХА (Когда будешь возжигать)",
    start: 361,
    end: 383,
    verses: 23,
  },
  {
    key: 10,
    chapterName: "БЕААЛОТХА (Когда будешь возжигать)",
    start: 384,
    end: 419,
    verses: 36,
  },
  {
    key: 11,
    chapterName: "БЕААЛОТХА (Когда будешь возжигать)",
    start: 420,
    end: 454,
    verses: 35,
  },
  {
    key: 12,
    chapterName: "БЕААЛОТХА (Когда будешь возжигать)",
    start: 455,
    end: 470,
    verses: 16,
  },
  {
    key: 13,
    chapterName: "ШЛАХ (Отправь)",
    start: 471,
    end: 503,
    verses: 33,
  },
  {
    key: 14,
    chapterName: "ШЛАХ (Отправь)",
    start: 504,
    end: 548,
    verses: 45,
  },
  {
    key: 15,
    chapterName: "ШЛАХ (Отправь)",
    start: 549,
    end: 589,
    verses: 41,
  },
  {
    key: 16,
    chapterName: "КОРАХ (Корах)",
    start: 590,
    end: 624,
    verses: 35,
  },
  {
    key: 17,
    chapterName: "КОРАХ (Корах)",
    start: 625,
    end: 652,
    verses: 28,
  },
  {
    key: 18,
    chapterName: "КОРАХ (Корах)",
    start: 653,
    end: 684,
    verses: 32,
  },
  {
    key: 19,
    chapterName: "ХУКАТ (Постановление)",
    start: 685,
    end: 706,
    verses: 22,
  },
  {
    key: 20,
    chapterName: "ХУКАТ (Постановление)",
    start: 707,
    end: 735,
    verses: 29,
  },
  {
    key: 21,
    chapterName: "ХУКАТ (Постановление)",
    start: 736,
    end: 770,
    verses: 35,
  },
  {
    key: 22,
    chapterName: "ХУКАТ (Постановление)",
    start: 771,
    end: 811,
    verses: 41,
  },
  {
    key: 23,
    chapterName: "БАЛАК (Балак)",
    start: 812,
    end: 841,
    verses: 30,
  },
  {
    key: 24,
    chapterName: "БАЛАК (Балак)",
    start: 842,
    end: 866,
    verses: 25,
  },
  {
    key: 25,
    chapterName: "БАЛАК (Балак)",
    start: 867,
    end: 884,
    verses: 18,
  },
  {
    key: 26,
    chapterName: "ПИНХАС (Пинхас)",
    start: 885,
    end: 949,
    verses: 65,
  },
  {
    key: 27,
    chapterName: "ПИНХАС (Пинхас)",
    start: 950,
    end: 972,
    verses: 23,
  },
  {
    key: 28,
    chapterName: "ПИНХАС (Пинхас)",
    start: 973,
    end: 1003,
    verses: 31,
  },
  {
    key: 29,
    chapterName: "ПИНХАС (Пинхас)",
    start: 1004,
    end: 1042,
    verses: 39,
  },
  {
    key: 30,
    chapterName: "ПИНХАС (Пинхас)",
    start: 1043,
    end: 1059,
    verses: 17,
  },
  {
    key: 31,
    chapterName: "МАТОТ (Колена)",
    start: 1060,
    end: 1113,
    verses: 54,
  },
  {
    key: 32,
    chapterName: "МАТОТ (Колена)",
    start: 1114,
    end: 1155,
    verses: 42,
  },
  {
    key: 33,
    chapterName: "МАСЕЭЙ (Переходы)",
    start: 1156,
    end: 1211,
    verses: 56,
  },
  {
    key: 34,
    chapterName: "МАСЕЭЙ (Переходы)",
    start: 1212,
    end: 1240,
    verses: 29,
  },
  {
    key: 35,
    chapterName: "МАСЕЭЙ (Переходы)",
    start: 1241,
    end: 1274,
    verses: 34,
  },
  {
    key: 36,
    chapterName: "МАСЕЭЙ (Переходы)",
    start: 1275,
    end: 1287,
    verses: 13,
  },
];

export default bemidbarChapters;
