const beresheetChapters = [
  {
    key: 1,
    subKey: 1,
    chapterName: "БЕРЕШИТ (В начале)",
    start: 0,
    end: 30,
    verses: 31,
  },
  {
    key: 2,
    subKey: 1,
    chapterName: "БЕРЕШИТ (В начале)",
    start: 31,
    end: 55,
    verses: 25,
  },
  {
    key: 3,
    subKey: 1,
    chapterName: "БЕРЕШИТ (В начале)",
    start: 56,
    end: 79,
    verses: 24,
  },
  {
    key: 4,
    subKey: 1,
    chapterName: "БЕРЕШИТ (В начале)",
    start: 80,
    end: 105,
    verses: 26,
  },
  {
    key: 5,
    subKey: 1,
    chapterName: "БЕРЕШИТ (В начале)",
    start: 106,
    end: 137,
    verses: 32,
  },
  {
    key: 6,
    subKey: 1,
    chapterName: "БЕРЕШИТ (В начале)",
    start: 138,
    end: 145,
    verses: 8,
  },
  {
    key: 6,
    subKey: 2,
    chapterName: "НОАХ (Ноах)",
    start: 146,
    end: 159,
    verses: 14,
  },
  {
    key: 7,
    subKey: 1,
    chapterName: "НОАХ (Ноах)",
    start: 160,
    end: 183,
    verses: 24,
  },
  {
    key: 8,
    subKey: 1,
    chapterName: "НОАХ (Ноах)",
    start: 184,
    end: 205,
    verses: 22,
  },
  {
    key: 9,
    subKey: 1,
    chapterName: "НОАХ (Ноах)",
    start: 206,
    end: 234,
    verses: 29,
  },
  {
    key: 10,
    subKey: 1,
    chapterName: "НОАХ (Ноах)",
    start: 235,
    end: 266,
    verses: 32,
  },
  {
    key: 11,
    subKey: 1,
    chapterName: "НОАХ (Ноах)",
    start: 267,
    end: 298,
    verses: 32,
  },
  {
    key: 12,
    subKey: 1,
    chapterName: "ЛЕХ-ЛЕХА (Иди к себе)",
    start: 299,
    end: 318,
    verses: 20,
  },
  {
    key: 13,
    subKey: 1,
    chapterName: "ЛЕХ-ЛЕХА (Иди к себе)",
    start: 319,
    end: 336,
    verses: 18,
  },
  {
    key: 14,
    subKey: 1,
    chapterName: "ЛЕХ-ЛЕХА (Иди к себе)",
    start: 337,
    end: 360,
    verses: 24,
  },
  {
    key: 15,
    subKey: 1,
    chapterName: "ЛЕХ-ЛЕХА (Иди к себе)",
    start: 361,
    end: 380,
    verses: 20,
  },
  {
    key: 16,
    subKey: 1,
    chapterName: "ЛЕХ-ЛЕХА (Иди к себе)",
    start: 381,
    end: 396,
    verses: 16,
  },
  {
    key: 17,
    subKey: 1,
    chapterName: "ЛЕХ-ЛЕХА (Иди к себе)",
    start: 397,
    end: 423,
    verses: 27,
  },
  {
    key: 18,
    subKey: 1,
    chapterName: "ВАЙЕРА (И явил)",
    start: 424,
    end: 456,
    verses: 33,
  },
  {
    key: 19,
    subKey: 1,
    chapterName: "ВАЙЕРА (И явил)",
    start: 457,
    end: 493,
    verses: 37,
  },
  {
    key: 20,
    subKey: 1,
    chapterName: "ВАЙЕРА (И явил)",
    start: 494,
    end: 511,
    verses: 18,
  },
  {
    key: 21,
    subKey: 1,
    chapterName: "ВАЙЕРА (И явил)",
    start: 512,
    end: 545,
    verses: 34,
  },
  {
    key: 22,
    subKey: 1,
    chapterName: "ВАЙЕРА (И явил)",
    start: 546,
    end: 569,
    verses: 24,
  },
  {
    key: 23,
    subKey: 1,
    chapterName: "ХАЕЙ САРА (Жизнь Сары)",
    start: 570,
    end: 593,
    verses: 24,
  },
  {
    key: 24,
    subKey: 1,
    chapterName: "ХАЕЙ САРА (Жизнь Сары)",
    start: 594,
    end: 660,
    verses: 67,
  },
  {
    key: 25,
    subKey: 1,
    chapterName: "ХАЕЙ САРА (Жизнь Сары)",
    start: 661,
    end: 678,
    verses: 18,
  },
  {
    key: 25,
    subKey: 2,
    chapterName: "ТОЛЬДОТ (Потомки)",
    start: 679,
    end: 694,
    verses: 16,
  },
  {
    key: 26,
    subKey: 1,
    chapterName: "ТОЛЬДОТ (Потомство)",
    start: 695,
    end: 729,
    verses: 35,
  },
  {
    key: 27,
    subKey: 1,
    chapterName: "ТОЛЬДОТ (Потомство)",
    start: 730,
    end: 775,
    verses: 46,
  },
  {
    key: 28,
    subKey: 1,
    chapterName: "ТОЛЬДОТ (Потомство)",
    start: 776,
    end: 784,
    verses: 9,
  },
  {
    key: 28,
    subKey: 2,
    chapterName: "ВАЙЕЦЕ (И вышел)",
    start: 785,
    end: 797,
    verses: 13,
  },
  {
    key: 29,
    subKey: 1,
    chapterName: "ВАЙЕЦЕ (И вышел)",
    start: 798,
    end: 832,
    verses: 35,
  },
  {
    key: 30,
    subKey: 1,
    chapterName: "ВАЙЕЦЕ (И вышел)",
    start: 833,
    end: 875,
    verses: 43,
  },
  {
    key: 31,
    subKey: 1,
    chapterName: "ВАЙЕЦЕ (И вышел)",
    start: 876,
    end: 929,
    verses: 54,
  },
  {
    key: 32,
    subKey: 1,
    chapterName: "ВАЙЕЦЕ (И вышел)",
    start: 930,
    end: 932,
    verses: 3,
  },
  {
    key: 32,
    subKey: 2,
    chapterName: "ВАИШЛАХ (И ПОСЛАЛ)",
    start: 933,
    end: 962,
    verses: 30,
  },
  {
    key: 33,
    subKey: 1,
    chapterName: "ВАИШЛАХ (И ПОСЛАЛ)",
    start: 963,
    end: 981,
    verses: 19,
  },
  {
    key: 34,
    subKey: 1,
    chapterName: "ВАИШЛАХ (И ПОСЛАЛ)",
    start: 982,
    end: 1012,
    verses: 31,
  },
  {
    key: 35,
    subKey: 1,
    chapterName: "ВАИШЛАХ (И ПОСЛАЛ)",
    start: 1013,
    end: 1040,
    verses: 28,
  },
  {
    key: 36,
    subKey: 1,
    chapterName: "ВАИШЛАХ (И ПОСЛАЛ)",
    start: 1041,
    end: 1083,
    verses: 43,
  },
  {
    key: 37,
    subKey: 1,
    chapterName: "ВАЙЕШЕВ (И поселился)",
    start: 1084,
    end: 1119,
    verses: 36,
  },
  {
    key: 38,
    subKey: 1,
    chapterName: "ВАЙЕШЕВ (И поселился)",
    start: 1120,
    end: 1150,
    verses: 31,
  },
  {
    key: 39,
    subKey: 1,
    chapterName: "ВАЙЕШЕВ (И поселился)",
    start: 1151,
    end: 1173,
    verses: 23,
  },
  {
    key: 40,
    subKey: 1,
    chapterName: "ВАЙЕШЕВ (И поселился)",
    start: 1174,
    end: 1196,
    verses: 23,
  },
  {
    key: 41,
    subKey: 1,
    chapterName: "МИКЕЦ (И поселился)",
    start: 1197,
    end: 1252,
    verses: 56,
  },
  {
    key: 42,
    subKey: 1,
    chapterName: "МИКЕЦ (И поселился)",
    start: 1253,
    end: 1290,
    verses: 38,
  },
  {
    key: 43,
    subKey: 1,
    chapterName: "МИКЕЦ (И поселился)",
    start: 1291,
    end: 1324,
    verses: 34,
  },
  {
    key: 44,
    subKey: 1,
    chapterName: "МИКЕЦ (И поселился)",
    start: 1325,
    end: 1341,
    verses: 17,
  },
  {
    key: 44,
    subKey: 2,
    chapterName: "ВАИГАШ (И подступил)",
    start: 1342,
    end: 1358,
    verses: 17,
  },
  {
    key: 45,
    subKey: 1,
    chapterName: "ВАИГАШ (И подступил)",
    start: 1359,
    end: 1386,
    verses: 28,
  },
  {
    key: 46,
    subKey: 1,
    chapterName: "ВАИГАШ (И подступил)",
    start: 1387,
    end: 1420,
    verses: 34,
  },
  {
    key: 47,
    subKey: 1,
    chapterName: "ВАИГАШ (И подступил)",
    start: 1421,
    end: 1447,
    verses: 27,
  },
  {
    key: 47,
    subKey: 2,
    chapterName: "ВАЙЕХИ (И жил)",
    start: 1448,
    end: 1451,
    verses: 4,
  },
  {
    key: 48,
    subKey: 1,
    chapterName: "ВАЙЕХИ (И жил)",
    start: 1452,
    end: 1473,
    verses: 22,
  },
  {
    key: 49,
    subKey: 1,
    chapterName: "ВАЙЕХИ (И жил)",
    start: 1474,
    end: 1506,
    verses: 33,
  },
  {
    key: 50,
    subKey: 1,
    chapterName: "ВАЙЕХИ (И жил)",
    start: 1507,
    end: 1532,
    verses: 26,
  },
];

export default beresheetChapters;
