const beresheetChapters = [
  {
    key: 1,
    chapterName: "БЕРЕШИТ (В начале)",
    start: 0,
    end: 30,
    verses: 31,
  },
  {
    key: 2,
    chapterName: "БЕРЕШИТ (В начале)",
    start: 31,
    end: 55,
    verses: 25,
  },
  {
    key: 3,
    chapterName: "БЕРЕШИТ (В начале)",
    start: 56,
    end: 79,
    verses: 24,
  },
  {
    key: 4,
    chapterName: "БЕРЕШИТ (В начале)",
    start: 80,
    end: 105,
    verses: 26,
  },
  {
    key: 5,
    chapterName: "БЕРЕШИТ (В начале)",
    start: 106,
    end: 137,
    verses: 32,
  },
  {
    key: 6,
    chapterName: "БЕРЕШИТ (В начале)",
    start: 138,
    end: 159,
    verses: 22,
  },
  {
    key: 7,
    chapterName: "НОАХ (Ноах)",
    start: 160,
    end: 183,
    verses: 24,
  },
  {
    key: 8,
    chapterName: "НОАХ (Ноах)",
    start: 184,
    end: 205,
    verses: 22,
  },
  {
    key: 9,
    chapterName: "НОАХ (Ноах)",
    start: 206,
    end: 234,
    verses: 29,
  },
  {
    key: 10,
    chapterName: "НОАХ (Ноах)",
    start: 235,
    end: 266,
    verses: 32,
  },
  {
    key: 11,
    chapterName: "НОАХ (Ноах)",
    start: 267,
    end: 298,
    verses: 32,
  },
  {
    key: 12,
    chapterName: "ЛЕХ-ЛЕХА (Иди к себе)",
    start: 299,
    end: 318,
    verses: 20,
  },
  {
    key: 13,
    chapterName: "ЛЕХ-ЛЕХА (Иди к себе)",
    start: 319,
    end: 336,
    verses: 18,
  },
  {
    key: 14,
    chapterName: "ЛЕХ-ЛЕХА (Иди к себе)",
    start: 337,
    end: 360,
    verses: 24,
  },
  {
    key: 15,
    chapterName: "ЛЕХ-ЛЕХА (Иди к себе)",
    start: 361,
    end: 380,
    verses: 20,
  },
  {
    key: 16,
    chapterName: "ЛЕХ-ЛЕХА (Иди к себе)",
    start: 381,
    end: 396,
    verses: 16,
  },
  {
    key: 17,
    chapterName: "ЛЕХ-ЛЕХА (Иди к себе)",
    start: 397,
    end: 423,
    verses: 27,
  },
  {
    key: 18,
    chapterName: "ВАЙЕРА (И явил)",
    start: 424,
    end: 456,
    verses: 33,
  },
  {
    key: 19,
    chapterName: "ВАЙЕРА (И явил)",
    start: 457,
    end: 494,
    verses: 38,
  },
  {
    key: 20,
    chapterName: "ВАЙЕРА (И явил)",
    start: 495,
    end: 512,
    verses: 18,
  },
  {
    key: 21,
    chapterName: "ВАЕРА (И явил)",
    start: 513,
    end: 546,
    verses: 34,
  },
  {
    key: 22,
    chapterName: "ВАЕРА (И явил)",
    start: 547,
    end: 570,
    verses: 24,
  },
  {
    key: 23,
    chapterName: "ХАЕЙ САРА (Жизнь Сары)",
    start: 571,
    end: 594,
    verses: 24,
  },
  {
    key: 24,
    chapterName: "ХАЕЙ САРА (Жизнь Сары)",
    start: 595,
    end: 664,
    verses: 70,
  },
  {
    key: 25,
    chapterName: "ТОЛЬДОТ (Потомки)",
    start: 665,
    end: 698,
    verses: 34,
  },
  {
    key: 26,
    chapterName: "ТОЛЬДОТ (Потомство)",
    start: 699,
    end: 733,
    verses: 35,
  },
  {
    key: 27,
    chapterName: "ТОЛЬДОТ (Потомство)",
    start: 734,
    end: 779,
    verses: 46,
  },
  {
    key: 28,
    chapterName: "ВАЙЕЦЕ (И вышел)",
    start: 780,
    end: 801,
    verses: 22,
  },
  {
    key: 29,
    chapterName: "ВАЙЕЦЕ (И вышел)",
    start: 802,
    end: 836,
    verses: 35,
  },
  {
    key: 30,
    chapterName: "ВАЙЕЦЕ (И вышел)",
    start: 837,
    end: 879,
    verses: 43,
  },
  {
    key: 31,
    chapterName: "ВАЙЕЦЕ (И вышел)",
    start: 880,
    end: 933,
    verses: 54,
  },
  {
    key: 32,
    chapterName: "ВАЙЕЦЕ (И вышел)",
    start: 934,
    end: 966,
    verses: 33,
  },
  {
    key: 33,
    chapterName: "ВАИШЛАХ (И послал)",
    start: 967,
    end: 985,
    verses: 19,
  },
  {
    key: 34,
    chapterName: "ВАИШЛАХ (И послал)",
    start: 986,
    end: 1016,
    verses: 31,
  },
  {
    key: 35,
    chapterName: "ВАИШЛАХ (И послал)",
    start: 1017,
    end: 1044,
    verses: 28,
  },
  {
    key: 36,
    chapterName: "ВАИШЛАХ (И послал)",
    start: 1045,
    end: 1087,
    verses: 43,
  },
  {
    key: 37,
    chapterName: "ВАЙЕШЕВ (И поселился)",
    start: 1088,
    end: 1123,
    verses: 36,
  },
  {
    key: 38,
    chapterName: "ВАЙЕШЕВ (И поселился)",
    start: 1124,
    end: 1154,
    verses: 31,
  },
  {
    key: 39,
    chapterName: "ВАЙЕШЕВ (И поселился)",
    start: 1155,
    end: 1177,
    verses: 23,
  },
  {
    key: 40,
    chapterName: "ВАЙЕШЕВ (И поселился)",
    start: 1178,
    end: 1200,
    verses: 23,
  },
  {
    key: 41,
    chapterName: "МИКЕЦ (И поселился)",
    start: 1201,
    end: 1256,
    verses: 56,
  },
  {
    key: 42,
    chapterName: "МИКЕЦ (И поселился)",
    start: 1257,
    end: 1294,
    verses: 38,
  },
  {
    key: 43,
    chapterName: "МИКЕЦ (И поселился)",
    start: 1295,
    end: 1328,
    verses: 34,
  },
  {
    key: 44,
    chapterName: "МИКЕЦ (И поселился)",
    start: 1329,
    end: 1362,
    verses: 34,
  },
  {
    key: 45,
    chapterName: "ВАИГАШ (И подступил)",
    start: 1363,
    end: 1390,
    verses: 28,
  },
  {
    key: 46,
    chapterName: "ВАИГАШ (И подступил)",
    start: 1391,
    end: 1424,
    verses: 34,
  },
  {
    key: 47,
    chapterName: "ВАИГАШ (И подступил)",
    start: 1425,
    end: 1455,
    verses: 31,
  },
  {
    key: 48,
    chapterName: "ВАЙЕХИ (И жил)",
    start: 1456,
    end: 1477,
    verses: 22,
  },
  {
    key: 49,
    chapterName: "ВАЙЕХИ (И жил)",
    start: 1478,
    end: 1510,
    verses: 33,
  },
  {
    key: 50,
    chapterName: "ВАЙЕХИ (И жил)",
    start: 1511,
    end: 1536,
    verses: 26,
  },
];

export default beresheetChapters;
