const dvarimChapters = [
  {
    key: 1,
    subKey: 1,
    chapterName: "ДВАРИМ(Слова)",
    start: 0,
    end: 45,
    verses: 46,
  },
  {
    key: 2,
    subKey: 1,
    chapterName: "ДВАРИМ(Слова)",
    start: 46,
    end: 82,
    verses: 37,
  },
  {
    key: 3,
    subKey: 1,
    chapterName: "ДВАРИМ(Слова)",
    start: 83,
    end: 104,
    verses: 22,
  },
  {
    key: 3,
    subKey: 2,
    chapterName: "ВАЭТХАНАН(И молил)",
    start: 105,
    end: 111,
    verses: 7,
  },
  {
    key: 4,
    subKey: 1,
    chapterName: "ВАЭТХАНАН(И молил)",
    start: 112,
    end: 160,
    verses: 49,
  },
  {
    key: 5,
    subKey: 1,
    chapterName: "ВАЭТХАНАН(И молил)",
    start: 161,
    end: 190,
    verses: 30,
  },
  {
    key: 6,
    subKey: 1,
    chapterName: "ВАЭТХАНАН(И молил)",
    start: 191,
    end: 215,
    verses: 25,
  },
  {
    key: 7,
    subKey: 1,
    chapterName: "ВАЭТХАНАН(И молил)",
    start: 216,
    end: 226,
    verses: 11,
  },
];

export default dvarimChapters;
