const dvarimChapters = [
  {
    key: 1,
    subKey: 1,
    chapterName: "ДВАРИМ (Слова)",
    start: 0,
    end: 45,
    verses: 46,
  },
  {
    key: 2,
    subKey: 1,
    chapterName: "ДВАРИМ (Слова)",
    start: 46,
    end: 82,
    verses: 37,
  },
  {
    key: 3,
    subKey: 1,
    chapterName: "ДВАРИМ (Слова)",
    start: 83,
    end: 104,
    verses: 22,
  },
  {
    key: 3,
    subKey: 2,
    chapterName: "ВАЭТХАНАН (И молил)",
    start: 105,
    end: 111,
    verses: 7,
  },
  {
    key: 4,
    subKey: 1,
    chapterName: "ВАЭТХАНАН (И молил)",
    start: 112,
    end: 160,
    verses: 49,
  },
  {
    key: 5,
    subKey: 1,
    chapterName: "ВАЭТХАНАН (И молил)",
    start: 161,
    end: 190,
    verses: 30,
  },
  {
    key: 6,
    subKey: 1,
    chapterName: "ВАЭТХАНАН (И молил)",
    start: 191,
    end: 215,
    verses: 25,
  },
  {
    key: 7,
    subKey: 1,
    chapterName: "ВАЭТХАНАН (И молил)",
    start: 216,
    end: 226,
    verses: 11,
  },
  {
    key: 7,
    subKey: 2,
    chapterName: "ЭКЕВ (За то, что)",
    start: 227,
    end: 241,
    verses: 15,
  },
  {
    key: 8,
    subKey: 1,
    chapterName: "ЭКЕВ (За то, что)",
    start: 242,
    end: 261,
    verses: 20,
  },
  {
    key: 9,
    subKey: 1,
    chapterName: "ЭКЕВ (За то, что)",
    start: 262,
    end: 290,
    verses: 29,
  },
  {
    key: 10,
    subKey: 1,
    chapterName: "ЭКЕВ (За то, что)",
    start: 291,
    end: 312,
    verses: 22,
  },
  {
    key: 11,
    subKey: 1,
    chapterName: "ЭКЕВ (За то, что)",
    start: 313,
    end: 337,
    verses: 25,
  },
  {
    key: 11,
    subKey: 2,
    chapterName: "РЕЭ (Смотри)",
    start: 338,
    end: 344,
    verses: 7,
  },
  {
    key: 12,
    subKey: 1,
    chapterName: "РЕЭ (Смотри)",
    start: 345,
    end: 375,
    verses: 31,
  },
  {
    key: 13,
    subKey: 1,
    chapterName: "РЕЭ (Смотри)",
    start: 376,
    end: 394,
    verses: 19,
  },
  {
    key: 14,
    subKey: 1,
    chapterName: "РЕЭ (Смотри)",
    start: 395,
    end: 423,
    verses: 29,
  },
  {
    key: 15,
    subKey: 1,
    chapterName: "РЕЭ (Смотри)",
    start: 424,
    end: 446,
    verses: 23,
  },
  {
    key: 16,
    subKey: 1,
    chapterName: "РЕЭ (Смотри)",
    start: 447,
    end: 463,
    verses: 17,
  },
  {
    key: 16,
    subKey: 2,
    chapterName: "ШОФТИМ (Судьи)",
    start: 464,
    end: 468,
    verses: 5,
  },
  {
    key: 17,
    subKey: 1,
    chapterName: "ШОФТИМ (Судьи)",
    start: 469,
    end: 488,
    verses: 20,
  },
  {
    key: 18,
    subKey: 1,
    chapterName: "ШОФТИМ (Судьи)",
    start: 489,
    end: 510,
    verses: 22,
  },
  {
    key: 19,
    subKey: 1,
    chapterName: "ШОФТИМ (Судьи)",
    start: 511,
    end: 531,
    verses: 21,
  },
  {
    key: 20,
    subKey: 1,
    chapterName: "ШОФТИМ (Судьи)",
    start: 532,
    end: 551,
    verses: 20,
  },
  {
    key: 21,
    subKey: 1,
    chapterName: "ШОФТИМ (Судьи)",
    start: 552,
    end: 560,
    verses: 9,
  },
  {
    key: 21,
    subKey: 2,
    chapterName: "КИ-ТЕЦЕ (Когда выйдешь)",
    start: 561,
    end: 574,
    verses: 14,
  },
  {
    key: 22,
    subKey: 1,
    chapterName: "КИ-ТЕЦЕ (Когда выйдешь)",
    start: 575,
    end: 603,
    verses: 29,
  },
  {
    key: 23,
    subKey: 1,
    chapterName: "КИ-ТЕЦЕ (Когда выйдешь)",
    start: 604,
    end: 629,
    verses: 26,
  },
  {
    key: 24,
    subKey: 1,
    chapterName: "КИ-ТЕЦЕ (Когда выйдешь)",
    start: 630,
    end: 651,
    verses: 22,
  },
  {
    key: 25,
    subKey: 1,
    chapterName: "КИ-ТЕЦЕ (Когда выйдешь)",
    start: 652,
    end: 670,
    verses: 19,
  },
  {
    key: 26,
    subKey: 1,
    chapterName: "КИ-ТАВО (Когда прийдешь)",
    start: 671,
    end: 689,
    verses: 19,
  },
  {
    key: 27,
    subKey: 1,
    chapterName: "КИ-ТАВО (Когда прийдешь)",
    start: 690,
    end: 715,
    verses: 26,
  },
  {
    key: 28,
    subKey: 1,
    chapterName: "КИ-ТАВО (Когда прийдешь)",
    start: 716,
    end: 784,
    verses: 69,
  },
  {
    key: 29,
    subKey: 1,
    chapterName: "КИ-ТАВО (Когда прийдешь)",
    start: 785,
    end: 792,
    verses: 8,
  },
  {
    key: 29,
    subKey: 2,
    chapterName: "НИЦАВИМ (Стоите)",
    start: 793,
    end: 812,
    verses: 20,
  },
  {
    key: 30,
    subKey: 1,
    chapterName: "НИЦАВИМ (Стоите)",
    start: 813,
    end: 832,
    verses: 20,
  },
  {
    key: 31,
    subKey: 1,
    chapterName: "ВАЙЕЛЕХ (И пошел)",
    start: 833,
    end: 862,
    verses: 30,
  },
  {
    key: 32,
    subKey: 1,
    chapterName: "ГААЗУ (Слушайте внимательно)",
    start: 863,
    end: 914,
    verses: 52,
  },
  {
    key: 33,
    subKey: 1,
    chapterName: "ВЕЗОТ ГА-БРАХА (Вот благословение)",
    start: 915,
    end: 943,
    verses: 29,
  },
  {
    key: 34,
    subKey: 1,
    chapterName: "ВЕЗОТ ГА-БРАХА (Вот благословение)",
    start: 944,
    end: 955,
    verses: 12,
  },
];

export default dvarimChapters;
