const schmotChapters = [
  {
    key: 1,
    chapterName: "ШМОТ (Имена)",
    start: 0,
    end: 21,
    verses: 22,
  },
  {
    key: 2,
    chapterName: "ШМОТ (Имена)",
    start: 22,
    end: 46,
    verses: 25,
  },
  {
    key: 3,
    chapterName: "ШМОТ (Имена)",
    start: 47,
    end: 68,
    verses: 22,
  },
  {
    key: 4,
    chapterName: "ШМОТ (Имена)",
    start: 69,
    end: 99,
    verses: 31,
  },
  {
    key: 5,
    chapterName: "ШМОТ (Имена)",
    start: 100,
    end: 122,
    verses: 23,
  },
  {
    key: 6,
    chapterName: "ШМОТ (Имена)",
    start: 123,
    end: 152,
    verses: 30,
  },
  {
    key: 7,
    chapterName: "ВАЭРА (И явился Я)",
    start: 153,
    end: 181,
    verses: 29,
  },
  {
    key: 8,
    chapterName: "ВАЭРА (И явился Я)",
    start: 182,
    end: 209,
    verses: 28,
  },
  {
    key: 9,
    chapterName: "ВАЭРА (И явился Я)",
    start: 210,
    end: 244,
    verses: 35,
  },
  {
    key: 10,
    chapterName: "БО (Пойди)",
    start: 245,
    end: 273,
    verses: 29,
  },
  {
    key: 11,
    chapterName: "БО (Пойди)",
    start: 274,
    end: 283,
    verses: 10,
  },
  {
    key: 12,
    chapterName: "БО (Пойди)",
    start: 284,
    end: 334,
    verses: 51,
  },
  {
    key: 13,
    chapterName: "БО (Пойди)",
    start: 335,
    end: 356,
    verses: 22,
  },
  {
    key: 14,
    chapterName: "БЕШАЛАХ (Когда отпустил)",
    start: 357,
    end: 387,
    verses: 31,
  },
  {
    key: 15,
    chapterName: "БЕШАЛАХ (Когда отпустил)",
    start: 388,
    end: 414,
    verses: 27,
  },
  {
    key: 16,
    chapterName: "БЕШАЛАХ (Когда отпустил)",
    start: 415,
    end: 449,
    verses: 35,
  },
  {
    key: 17,
    chapterName: "БЕШАЛАХ (Когда отпустил)",
    start: 450,
    end: 465,
    verses: 16,
  },
  {
    key: 18,
    chapterName: "ИТРО (Итро)",
    start: 466,
    end: 492,
    verses: 27,
  },
  {
    key: 19,
    chapterName: "ИТРО (Итро)",
    start: 493,
    end: 517,
    verses: 25,
  },
  {
    key: 20,
    chapterName: "ИТРО (Итро)",
    start: 518,
    end: 539,
    verses: 22,
  },
  {
    key: 21,
    chapterName: "МИШПАТИМ (Законы)",
    start: 540,
    end: 576,
    verses: 37,
  },
  {
    key: 22,
    chapterName: "МИШПАТИМ (Законы)",
    start: 577,
    end: 606,
    verses: 30,
  },
  {
    key: 23,
    chapterName: "МИШПАТИМ (Законы)",
    start: 607,
    end: 639,
    verses: 33,
  },
  {
    key: 24,
    chapterName: "МИШПАТИМ (Законы)",
    start: 640,
    end: 657,
    verses: 18,
  },
  {
    key: 25,
    chapterName: "ТРУМА (Приношение)",
    start: 658,
    end: 697,
    verses: 40,
  },
  {
    key: 26,
    chapterName: "ТРУМА (Приношение)",
    start: 698,
    end: 734,
    verses: 37,
  },
  {
    key: 27,
    chapterName: "ТРУМА (Приношение)",
    start: 735,
    end: 755,
    verses: 21,
  },
  {
    key: 28,
    chapterName: "ТЕЦАВЕ (Повели)",
    start: 756,
    end: 798,
    verses: 43,
  },
  {
    key: 29,
    chapterName: "ТЕЦАВЕ (Повели)",
    start: 799,
    end: 844,
    verses: 46,
  },
  {
    key: 30,
    chapterName: "ТЕЦАВЕ (Повели)",
    start: 845,
    end: 882,
    verses: 38,
  },
  {
    key: 31,
    chapterName: "ТИСА (Когда поднимешь)",
    start: 883,
    end: 900,
    verses: 18,
  },
  {
    key: 32,
    chapterName: "ТИСА (Когда поднимешь)",
    start: 901,
    end: 935,
    verses: 35,
  },
  {
    key: 33,
    chapterName: "ТИСА (Когда поднимешь)",
    start: 936,
    end: 958,
    verses: 23,
  },
  {
    key: 34,
    chapterName: "ТИСА (Когда поднимешь)",
    start: 959,
    end: 993,
    verses: 35,
  },
  {
    key: 35,
    chapterName: "ВАЯКГЕЛЬ (И собрал общину)",
    start: 994,
    end: 1028,
    verses: 35,
  },
  {
    key: 36,
    chapterName: "ВАЯКГЕЛЬ (И собрал общину)",
    start: 1029,
    end: 1066,
    verses: 38,
  },
  {
    key: 37,
    chapterName: "ВАЯКГЕЛЬ (И собрал общину)",
    start: 1067,
    end: 1095,
    verses: 29,
  },
  {
    key: 38,
    chapterName: "ВАЯКГЕЛЬ (И собрал общину)",
    start: 1096,
    end: 1126,
    verses: 31,
  },
  {
    key: 39,
    chapterName: "ПЕКУДЕЙ (Отчёты)",
    start: 1127,
    end: 1169,
    verses: 43,
  },
  {
    key: 40,
    chapterName: "ПЕКУДЕЙ (Отчёты)",
    start: 1170,
    end: 1206,
    verses: 37,
  },
];

export default schmotChapters;
