const vaikraChapters = [
  {
    key: 1,
    chapterName: "ВАИКРА (И призвал)",
    start: 0,
    end: 16,
    verses: 17,
  },
  {
    key: 2,
    chapterName: "ВАИКРА (И призвал)",
    start: 17,
    end: 32,
    verses: 16,
  },
  {
    key: 3,
    chapterName: "ВАИКРА (И призвал)",
    start: 33,
    end: 49,
    verses: 17,
  },
  {
    key: 4,
    chapterName: "ВАИКРА (И призвал)",
    start: 50,
    end: 84,
    verses: 35,
  },
  {
    key: 5,
    chapterName: "ВАИКРА (И призвал)",
    start: 85,
    end: 110,
    verses: 26,
  },
  {
    key: 6,
    chapterName: "ЦАВ (Прикажи)",
    start: 111,
    end: 133,
    verses: 23,
  },
  {
    key: 7,
    chapterName: "ЦАВ (Прикажи)",
    start: 134,
    end: 171,
    verses: 38,
  },
  {
    key: 8,
    chapterName: "ЦАВ (Прикажи)",
    start: 172,
    end: 207,
    verses: 36,
  },
  {
    key: 9,
    chapterName: "ШМИНИ (Восьмой)",
    start: 208,
    end: 231,
    verses: 24,
  },
  {
    key: 10,
    chapterName: "ШМИНИ (Восьмой)",
    start: 232,
    end: 251,
    verses: 20,
  },
  {
    key: 11,
    chapterName: "ШМИНИ (Восьмой)",
    start: 252,
    end: 298,
    verses: 47,
  },
  {
    key: 12,
    chapterName: "ТАЗРИА (Когда зачнёт)",
    start: 299,
    end: 306,
    verses: 8,
  },
  {
    key: 13,
    chapterName: "ТАЗРИА (Когда зачнет)",
    start: 307,
    end: 365,
    verses: 59,
  },
  {
    key: 14,
    chapterName: "МЕЦОРА (Прокажённый)",
    start: 366,
    end: 422,
    verses: 57,
  },
  {
    key: 15,
    chapterName: "МЕЦОРА (Прокажённый)",
    start: 423,
    end: 455,
    verses: 33,
  },
  {
    key: 16,
    chapterName: "АХАРЕЙ МОТ (После смерти)",
    start: 456,
    end: 489,
    verses: 34,
  },
  {
    key: 17,
    chapterName: "АХАРЕЙ МОТ (После смерти)",
    start: 490,
    end: 505,
    verses: 16,
  },
  {
    key: 18,
    chapterName: "АХАРЕЙ МОТ (После смерти)",
    start: 506,
    end: 535,
    verses: 30,
  },
  {
    key: 19,
    chapterName: "КДОШИМ (Святые)",
    start: 536,
    end: 572,
    verses: 37,
  },
  {
    key: 20,
    chapterName: "КДОШИМ (Святые)",
    start: 573,
    end: 599,
    verses: 27,
  },
  {
    key: 21,
    chapterName: "ЭМОР (Скажи)",
    start: 600,
    end: 623,
    verses: 24,
  },
  {
    key: 22,
    chapterName: "ЭМОР (Скажи)",
    start: 624,
    end: 656,
    verses: 33,
  },
  {
    key: 23,
    chapterName: "ЭМОР (Скажи)",
    start: 657,
    end: 700,
    verses: 44,
  },
  {
    key: 24,
    chapterName: "ЭМОР (Скажи)",
    start: 701,
    end: 723,
    verses: 23,
  },
  {
    key: 25,
    chapterName: "БЕГАР (На горе)",
    start: 724,
    end: 778,
    verses: 55,
  },
  {
    key: 26,
    chapterName: "БЕГАР (На горе)",
    start: 779,
    end: 826,
    verses: 48,
  },
  {
    key: 27,
    chapterName: "БЕХУКОТАЙ (Если будете следовать Моим законам)",
    start: 827,
    end: 860,
    verses: 34,
  },
];

export default vaikraChapters;
