export const holidayTitleMap: { pattern: RegExp; translation: string }[] = [
  // === Major holidays ===
  { pattern: /^Rosh Hashana( \d+)?$/, translation: "Рош ха-Шана" },
  { pattern: /^Rosh Hashana II$/, translation: "Рош ха-Шана II" },
  { pattern: /^Erev Rosh Hashana$/, translation: "Накануне Рош ха-Шана" },
  { pattern: /^Yom Kippur$/, translation: "Йом Кипур" },
  { pattern: /^Erev Yom Kippur$/, translation: "Накануне Йом Кипур" },
  { pattern: /^Sukkot I$/, translation: "Суккот I" },
  { pattern: /^Sukkot II$/, translation: "Суккот II" },
  {
    pattern: /^Sukkot III \(CH’’M\)$/,
    translation: "Суккот III (Холь а-Моэд)",
  },
  { pattern: /^Sukkot IV \(CH’’M\)$/, translation: "Суккот IV (Холь а-Моэд)" },
  { pattern: /^Sukkot V \(CH’’M\)$/, translation: "Суккот V (Холь а-Моэд)" },
  { pattern: /^Sukkot VI \(CH’’M\)$/, translation: "Суккот VI (Холь а-Моэд)" },
  {
    pattern: /^Sukkot VII \(Hoshana Raba\)$/,
    translation: "Суккот VII (Ошанна Раба)",
  },
  { pattern: /^Shmini Atzeret$/, translation: "Шмини Ацерет" },
  { pattern: /^Simchat Torah$/, translation: "Симхат Тора" },

  { pattern: /^Pesach I$/, translation: "Песах I" },
  { pattern: /^Pesach II$/, translation: "Песах II" },
  { pattern: /^Pesach III \(CH’’M\)$/, translation: "Песах III (Холь а-Моэд)" },
  { pattern: /^Pesach IV \(CH’’M\)$/, translation: "Песах IV (Холь а-Моэд)" },
  { pattern: /^Pesach V \(CH’’M\)$/, translation: "Песах V (Холь а-Моэд)" },
  { pattern: /^Pesach VI \(CH’’M\)$/, translation: "Песах VI (Холь а-Моэд)" },
  { pattern: /^Pesach VII$/, translation: "Песах VII" },
  { pattern: /^Pesach VIII$/, translation: "Песах VIII" },
  { pattern: /^Erev Pesach$/, translation: "Накануне Песах" },

  { pattern: /^Shavuot I$/, translation: "Шавуот I" },
  { pattern: /^Shavuot II$/, translation: "Шавуот II" },
  { pattern: /^Erev Shavuot$/, translation: "Накануне Шавуот" },

  // === Minor holidays ===
  { pattern: /^Purim$/, translation: "Пурим" },
  { pattern: /^Erev Purim$/, translation: "Накануне Пурим" },
  { pattern: /^Shushan Purim$/, translation: "Шушан Пурим" },
  { pattern: /^Purim Meshulash$/, translation: "Пурим Мешулаш" },
  { pattern: /^Purim Katan$/, translation: "Пурим Катан" },
  { pattern: /^Shushan Purim Katan$/, translation: "Шушан Пурим Катан" },
  { pattern: /^Tu BiShvat$/, translation: "Ту би-Шват" },
  { pattern: /^Tu B’Av$/, translation: "Ту бе-Ав" },
  { pattern: /^Lag BaOmer$/, translation: "Лаг ба-Омер" },
  { pattern: /^Pesach Sheni$/, translation: "Песах Шени" },
  { pattern: /^Leil Selichot$/, translation: "Лейль Слихот" },
  { pattern: /^Chag HaBanot$/, translation: "Хаг Ха-Банот" },
  {
    pattern: /^Rosh Hashana LaBehemot$/,
    translation: "Рош ха-Шана для животных",
  },

  // === Posts ===
  { pattern: /^Erev Tish’a B’Av$/, translation: "Накануне Тиша бе-Ав" },
  { pattern: /^Tish’a B’Av$/, translation: "Тиша бе-Ав" },
  {
    pattern: /^Tish’a B’Av \(observed\)$/,
    translation: "Тиша бе-Ав (перенос)",
  },

  // === Chanukah ===
  { pattern: /^Chanukah: 1 Candle$/, translation: "Ханука: 1 свеча" },
  { pattern: /^Chanukah: 2 Candles$/, translation: "Ханука: 2 свечи" },
  { pattern: /^Chanukah: 3 Candles$/, translation: "Ханука: 3 свечи" },
  { pattern: /^Chanukah: 4 Candles$/, translation: "Ханука: 4 свечи" },
  { pattern: /^Chanukah: 5 Candles$/, translation: "Ханука: 5 свечей" },
  { pattern: /^Chanukah: 6 Candles$/, translation: "Ханука: 6 свечей" },
  { pattern: /^Chanukah: 7 Candles$/, translation: "Ханука: 7 свечей" },
  { pattern: /^Chanukah: 8 Candles$/, translation: "Ханука: 8 свечей" },
  { pattern: /^Chanukah: 8th Day$/, translation: "Ханука: 8-й день" },

  // === Parashat ===
  { pattern: /^Parashat Bereshit$/, translation: "Парашат Берешит" },
  { pattern: /^Parashat Noach$/, translation: "Парашат Ноах" },
  { pattern: /^Parashat Lech-Lecha$/, translation: "Парашат Лех-Леха" },
  { pattern: /^Parashat Vayera$/, translation: "Парашат Ваейра" },
  { pattern: /^Parashat Chayei Sara$/, translation: "Парашат Хаей Сара" },
  { pattern: /^Parashat Toldot$/, translation: "Парашат Толдот" },
  { pattern: /^Parashat Vayetzei$/, translation: "Парашат Ваецей" },
  { pattern: /^Parashat Vayishlach$/, translation: "Парашат Ваишлах" },
  { pattern: /^Parashat Vayeshev$/, translation: "Парашат Ваешев" },
  { pattern: /^Parashat Miketz$/, translation: "Парашат Микец" },
  { pattern: /^Parashat Vayigash$/, translation: "Парашат Ваигаш" },
  { pattern: /^Parashat Vayechi$/, translation: "Парашат Ваехи" },

  { pattern: /^Parashat Shemot$/, translation: "Парашат Шмот" },
  { pattern: /^Parashat Vaera$/, translation: "Парашат Ваэра" },
  { pattern: /^Parashat Bo$/, translation: "Парашат Бо" },
  { pattern: /^Parashat Beshalach$/, translation: "Парашат Бешалах" },
  { pattern: /^Parashat Yitro$/, translation: "Парашат Итро" },
  { pattern: /^Parashat Mishpatim$/, translation: "Парашат Мишпатим" },
  { pattern: /^Parashat Terumah$/, translation: "Парашат Трума" },
  { pattern: /^Parashat Tetzaveh$/, translation: "Парашат Тецаве" },
  { pattern: /^Parashat Ki Tisa$/, translation: "Парашат Ки Тиса" },
  { pattern: /^Parashat Vayakhel$/, translation: "Парашат Ваякель" },
  { pattern: /^Parashat Pekudei$/, translation: "Парашат Пекудей" },
  {
    pattern: /^Parashat Vayakhel-Pekudei$/,
    translation: "Парашат Ваякель-Пекудей",
  },

  { pattern: /^Parashat Vayikra$/, translation: "Парашат Ваикра" },
  { pattern: /^Parashat Tzav$/, translation: "Парашат Цав" },
  { pattern: /^Parashat Shmini$/, translation: "Парашат Шмини" },
  { pattern: /^Parashat Tazria$/, translation: "Парашат Тазрия" },
  { pattern: /^Parashat Metzora$/, translation: "Парашат Мецора" },
  {
    pattern: /^Parashat Tazria-Metzora$/,
    translation: "Парашат Тазрия-Мецора",
  },
  { pattern: /^Parashat Achrei Mot$/, translation: "Парашат Ахарей Мот" },
  { pattern: /^Parashat Kedoshim$/, translation: "Парашат Кдошим" },
  {
    pattern: /^Parashat Achrei Mot-Kedoshim$/,
    translation: "Парашат Ахарей Мот-Кдошим",
  },

  { pattern: /^Parashat Emor$/, translation: "Парашат Эмор" },
  { pattern: /^Parashat Behar$/, translation: "Парашат Бехар" },
  { pattern: /^Parashat Bechukotai$/, translation: "Парашат Бехукотай" },
  {
    pattern: /^Parashat Behar-Bechukotai$/,
    translation: "Парашат Бехар-Бехукотай",
  },

  { pattern: /^Parashat Bamidbar$/, translation: "Парашат Бемидбар" },
  { pattern: /^Parashat Nasso$/, translation: "Парашат Насо" },
  { pattern: /^Parashat Beha’alotcha$/, translation: "Парашат Беаалотха" },
  { pattern: /^Parashat Sh’lach$/, translation: "Парашат Шлах" },
  { pattern: /^Parashat Korach$/, translation: "Парашат Корах" },
  { pattern: /^Parashat Chukat$/, translation: "Парашат Хукат" },
  { pattern: /^Parashat Balak$/, translation: "Парашат Балака" },
  { pattern: /^Parashat Chukat-Balak$/, translation: "Парашат Хукат-Балак" },

  { pattern: /^Parashat Pinchas$/, translation: "Парашат Пинхас" },
  { pattern: /^Parashat Matot$/, translation: "Парашат Матот" },
  { pattern: /^Parashat Masei$/, translation: "Парашат Масей" },
  { pattern: /^Parashat Matot-Masei$/, translation: "Парашат Матот-Масей" },

  { pattern: /^Parashat Devarim$/, translation: "Парашат Дварим" },
  { pattern: /^Parashat Vaetchanan$/, translation: "Парашат Ваэтханан" },
  { pattern: /^Parashat Eikev$/, translation: "Парашат Экев" },
  { pattern: /^Parashat Re’eh$/, translation: "Парашат Реэ" },
  { pattern: /^Parashat Shoftim$/, translation: "Парашат Шофтим" },
  { pattern: /^Parashat Ki Teitzei$/, translation: "Парашат Ки Тецей" },
  { pattern: /^Parashat Ki Tavo$/, translation: "Парашат Ки Таво" },
  { pattern: /^Parashat Nitzavim$/, translation: "Парашат Ницавим" },
  { pattern: /^Parashat Vayeilech$/, translation: "Парашат Ваейлех" },
  {
    pattern: /^Parashat Nitzavim-Vayeilech$/,
    translation: "Парашат Ницавим-Ваейлех",
  },
  { pattern: /^Parashat Ha’azinu$/, translation: "Парашат Аазину" },

  // === Rosh Chodesh ===
  { pattern: /^Rosh Chodesh.*$/, translation: "Рош Ходеш" },
];
