export const parashatLinks: Record<string, string> = {
  //beresheet
  "Parashat Bereshit": "/books/tora/beresheet/1",
  "Parashat Noach": "/books/tora/beresheet/6/2",
  "Parashat Lech-Lecha": "/books/tora/beresheet/12",
  "Parashat Vayera": "/books/tora/beresheet/18",
  "Parashat Chayei Sara": "/books/tora/beresheet/23",
  "Parashat Toldot": "/books/tora/beresheet/25/2",
  "Parashat Vayetzei": "/books/tora/beresheet/28/2",
  "Parashat Vayishlach": "/books/tora/beresheet/32/2",
  "Parashat Vayeshev": "/books/tora/beresheet/37",
  "Parashat Miketz": "/books/tora/beresheet/41",
  "Parashat Vayigash": "/books/tora/beresheet/44/2",
  "Parashat Vayechi": "/books/tora/beresheet/47/2",

  //schmot
  "Parashat Shemot": "/books/tora/schmot/1",
  "Parashat Vaera": "/books/tora/schmot/6/2",
  "Parashat Bo": "/books/tora/schmot/10/2",
  "Parashat Beshalach": "/books/tora/schmot/13/2",
  "Parashat Yitro": "/books/tora/schmot/18",
  "Parashat Mishpatim": "/books/tora/schmot/21",
  "Parashat Terumah": "/books/tora/schmot/25",
  "Parashat Tetzaveh": "/books/tora/schmot/27/2",
  "Parashat Ki Tisa": "/books/tora/schmot/30/2",
  "Parashat Vayakhel": "/books/tora/schmot/35",
  "Parashat Pekudei": "/books/tora/schmot/38/2",
  "Parashat Vayakhel-Pekudei": "/books/tora/schmot/35",

  //vaikra
  "Parashat Vayikra": "/books/tora/vaikra/1",
  "Parashat Tzav": "/books/tora/vaikra/6",
  "Parashat Shmini": "/books/tora/vaikra/9",
  "Parashat Tazria": "/books/tora/vaikra/12",
  "Parashat Metzora": "/books/tora/vaikra/14",
  "Parashat Tazria-Metzora": "/books/tora/vaikra/12",
  "Parashat Achrei Mot": "/books/tora/vaikra/16",
  "Parashat Kedoshim": "/books/tora/vaikra/19",
  "Parashat Achrei Mot-Kedoshim": "/books/tora/vaikra/16",
  "Parashat Emor": "/books/tora/vaikra/21",
  "Parashat Behar": "/books/tora/vaikra/25",
  "Parashat Bechukotai": "/books/tora/vaikra/26/2",
  "Parashat Behar-Bechukotai": "/books/tora/vaikra/25",

  //bemidbar
  "Parashat Bamidbar": "/books/tora/bemidbar/1",
  "Parashat Nasso": "/books/tora/bemidbar/4/2",
  "Parashat Beha’alotcha": "/books/tora/bemidbar/8",
  "Parashat Sh’lach": "/books/tora/bemidbar/13",
  "Parashat Korach": "/books/tora/bemidbar/16",
  "Parashat Chukat": "/books/tora/bemidbar/19",
  "Parashat Balak": "/books/tora/bemidbar/22/2",
  "Parashat Chukat-Balak": "/books/tora/bemidbar/19",
  "Parashat Pinchas": "/books/tora/bemidbar/25/2",
  "Parashat Matot": "/books/tora/bemidbar/30/2",
  "Parashat Masei": "/books/tora/bemidbar/33",
  "Parashat Matot-Masei": "/books/tora/bemidbar/30/2",

  //dvarim
  "Parashat Devarim": "/books/tora/dvarim/1",
  "Parashat Vaetchanan": "/books/tora/dvarim/3/2",
  //   "Parashat Eikev": "/books/tora/dvarim/7",
  //   "Parashat Re’eh": "/books/tora/dvarim/11",
  //   "Parashat Shoftim": "/books/tora/dvarim/16",
  //   "Parashat Ki Teitzei": "/books/tora/dvarim/21",
  //   "Parashat Ki Tavo": "/books/tora/dvarim/26",
  //   "Parashat Nitzavim": "/books/tora/dvarim/29",
  //   "Parashat Vayeilech": "/books/tora/dvarim/31",
  //   "Parashat Nitzavim-Vayeilech": "/books/tora/dvarim/29",
  //   "Parashat Ha’azinu": "/books/tora/dvarim/32",
};
